name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PEM_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy application via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Navigate to your app directory
          cd /var/www/html/sharkweb

          # If the directory is empty or not initialized, clone the repo
          if [ ! -d ".git" ]; then
            git clone https://github.com/sivajigroups/shark-pos-api.git .
          else
            git pull origin main
          fi

          # Install dependencies and restart the app with PM2
          npm install
          pm2 restart all || pm2 start src/index.js
        EOF
